const containerBackgroundBoxShadow = `0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)`

export const themes = {
  dark: {
    foreground: "#BFC7D5",
    containerBackground: "#292D3E",
    containerBorder: "transparent",
    containerForeground: "#BFC7D5",
    highlighterWrong: "#ff7769",
    highlighterRight: "#219540",
    highlighterUnanswered: "#bdc1c6",
    optionButtonUnansweredBorder: "#ebf8ff",
    optionButtonUnansweredText: "#FFFFFF",
    optionButtonUnansweredBackground: "transparent",
    optionButtonRightBorder: "#ebf8ff",
    optionButtonRightText: "#FFFFFF",
    optionButtonRightBackground: "#219540",
    optionButtonWrongBorder: "#ebf8ff",
    optionButtonWrongText: "#FFFFFF",
    optionButtonWrongBackground: "#ff7769",
    containerBackgroundBoxShadow,
  },
  blacknwhite: {
    foreground: "#FFFFFF",
    containerBackground: "#000000",
    containerBorder: "transparent",
    containerForeground: "#ebf8ff",
    highlighterWrong: "#ff7769",
    highlighterRight: "#219540",
    highlighterUnanswered: "#bdc1c6",
    optionButtonUnansweredBorder: "#808080",
    optionButtonUnansweredText: "#FFFFFF",
    optionButtonUnansweredBackground: "transparent",
    optionButtonRightBorder: "transparent",
    optionButtonRightText: "#FFFFFF",
    optionButtonRightBackground: "#219540",
    optionButtonWrongBorder: "transparent",
    optionButtonWrongText: "#FFFFFF",
    optionButtonWrongBackground: "#ff7769",
    containerBackgroundBoxShadow,
  },
  blue: {
    primary: "#FFFFFF",
    foreground: "#000000",
    secondary: "#2F80ED",
    containerBackground: "#FFFFFF",
    containerBorder: "#b5d2f9",
    containerForeground: "#000000",
    highlighterWrong: "#ff7769",
    highlighterRight: "#2F80ED",
    highlighterUnanswered: "#bdc1c6",
    optionButtonUnansweredBorder: "#2F80ED",
    optionButtonUnansweredText: "#2F80ED",
    optionButtonUnansweredBackground: "#FFFFFF",
    optionButtonRightBorder: "#ebf8ff",
    optionButtonRightText: "#FFFFFF",
    optionButtonRightBackground: "#2F80ED",
    optionButtonWrongBorder: "#FFFFFF",
    optionButtonWrongText: "#FFFFFF",
    optionButtonWrongBackground: "#ff7769",
    containerBackgroundBoxShadow,
  },
  palenight: {
    foreground: "#BFC7D5",
    containerBackground: "#292D3E",
    containerBorder: "#e3dede",
    containerForeground: "#BFC7D5",
    highlighterWrong: "#ff7769",
    highlighterRight: "#219540",
    highlighterUnanswered: "#bdc1c6",
    optionButtonUnansweredBorder: "#ebf8ff29",
    optionButtonUnansweredText: "#ffffff",
    optionButtonUnansweredBackground: "#2e334b",
    optionButtonRightBorder: "#ebf8ff29",
    optionButtonRightText: "#FFFFFF",
    optionButtonRightBackground: "#219540",
    optionButtonWrongBorder: "#ebf8ff29",
    optionButtonWrongText: "#FFFFFF",
    optionButtonWrongBackground: "#ff7769",
    containerBackgroundBoxShadow,
  },
  nigeria: {
    foreground: "#4285f4",
    containerBackground: "#FFFFFF",
    containerBorder: "#e3dede",
    containerForeground: "#000000",
    highlighterWrong: "#ff7769",
    highlighterRight: "#219540",
    highlighterUnanswered: "#808080",
    optionButtonUnansweredBorder: "#4285f4",
    optionButtonUnansweredText: "#4285f4",
    optionButtonUnansweredBackground: "#FFFFFF",
    optionButtonRightBorder: "#ebf8ff29",
    optionButtonRightText: "#FFFFFF",
    optionButtonRightBackground: "#219540",
    optionButtonWrongBorder: "#ebf8ff29",
    optionButtonWrongText: "#FFFFFF",
    optionButtonWrongBackground: "#ff7769",
    containerBackgroundBoxShadow,
  },
  cobalt: {
    foreground: "#BFC7D5",
    containerBackground: "#193549",
    containerBorder: "#e3dede",
    containerForeground: "#BFC7D5",
    highlighterWrong: "#ff7769",
    highlighterRight: "#219540",
    highlighterUnanswered: "#bdc1c6",
    optionButtonUnansweredBorder: "#ffc60030",
    optionButtonUnansweredText: "#ffc600",
    optionButtonUnansweredBackground: "#0b2233",
    optionButtonRightBorder: "#ebf8ff",
    optionButtonRightText: "#ffffff",
    optionButtonRightBackground: "#219540",
    optionButtonWrongBorder: "#ebf8ff",
    optionButtonWrongText: "#ffffff",
    optionButtonWrongBackground: "#ff7769",
    containerBackgroundBoxShadow,
  },
}

export const themesKeys = Object.keys(themes)
